# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import tweet_feed.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tweet_feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='tweet',
            name='content',
            field=models.CharField(max_length=140, validators=[tweet_feed.validators.validate_content]),
        ),
    ]
